//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server.webship.solver.sk", ConfigurationName="ServiceReference1.WebshipWebService")]
    public interface WebshipWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="testReturn")]
        System.Threading.Tasks.Task<string> testAsync(string test);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createShipmentReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServiceShipmnetResult> createShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, int webServiceShipmentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createCifShipmentReturn")]
        System.Threading.Tasks.Task<ServiceReference1.CreateCifShipmentResult> createCifShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, int webServiceShipmentType);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createAndPrintCifShipmentReturn")]
        System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentResult> createAndPrintCifShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createAndPrintCifShipmentWithSettingsReturn")]
        System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentWithSettingsResult> createAndPrintCifShipmentWithSettingsAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, ServiceReference1.PrintingSettings printingSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createAndPrintCifShipmentReturn")]
        System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentResult> createAndPrintCifShipmentWithSettings2Async(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, ServiceReference1.PrintingSettings printingSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createMipShipmentReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServiceShipmnetResult> createMipShipmentAsync(string name, string password, ServiceReference1.MipWebserviceShipment mipWebserviceShipment);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="uploadMipShipmentsReturn")]
        System.Threading.Tasks.Task<ServiceReference1.MipWebserviceUploadResult> uploadMipShipmentsAsync(string name, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.finishAndPrintOrdersResponse> finishAndPrintOrdersAsync(ServiceReference1.finishAndPrintOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="printSDDshipmentsReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServiceSddPrintResult> printSDDshipmentsAsync(string aUserName, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="printLabelsWithSettingsReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printLabelsWithSettingsAsync(string aUserName, string aPassword, ServiceReference1.PrintingSettings aPrintingSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="printShipmentLabelsReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printShipmentLabelsAsync(string aUserName, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="printEndOfDayReturn")]
        System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printEndOfDayAsync(string aUserName, string aPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.createCifShipmentsResponse> createCifShipmentsAsync(ServiceReference1.createCifShipmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.createOrdersResponse> createOrdersAsync(ServiceReference1.createOrdersRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class WebServiceShipment
    {
        
        private Cod codField;
        
        private ShipmentAddress deliveryaddressField;
        
        private string insurvalueField;
        
        private string notifytypeField;
        
        private WebServicePackage[] packagesField;
        
        private ShipmentAddress pickupaddressField;
        
        private string productdescField;
        
        private System.Nullable<bool> recipientpayField;
        
        private bool recipientpayFieldSpecified;
        
        private System.Nullable<bool> returnshipmentField;
        
        private bool returnshipmentFieldSpecified;
        
        private System.Nullable<bool> returnlabelField;
        
        private bool returnlabelFieldSpecified;
        
        private System.Nullable<bool> saturdayshipmentField;
        
        private bool saturdayshipmentFieldSpecified;
        
        private string servicenameField;
        
        private string deliveryremarkField;
        
        private ShipmentPickup shipmentpickupField;
        
        private System.Nullable<bool> telField;
        
        private bool telFieldSpecified;
        
        private string unitsField;
        
        private string deliverytypeField;
        
        private ShipmentService[] servicesField;
        
        private int codattributeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public Cod cod
        {
            get
            {
                return this.codField;
            }
            set
            {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ShipmentAddress deliveryaddress
        {
            get
            {
                return this.deliveryaddressField;
            }
            set
            {
                this.deliveryaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string insurvalue
        {
            get
            {
                return this.insurvalueField;
            }
            set
            {
                this.insurvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string notifytype
        {
            get
            {
                return this.notifytypeField;
            }
            set
            {
                this.notifytypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public WebServicePackage[] packages
        {
            get
            {
                return this.packagesField;
            }
            set
            {
                this.packagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public ShipmentAddress pickupaddress
        {
            get
            {
                return this.pickupaddressField;
            }
            set
            {
                this.pickupaddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string productdesc
        {
            get
            {
                return this.productdescField;
            }
            set
            {
                this.productdescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<bool> recipientpay
        {
            get
            {
                return this.recipientpayField;
            }
            set
            {
                this.recipientpayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recipientpaySpecified
        {
            get
            {
                return this.recipientpayFieldSpecified;
            }
            set
            {
                this.recipientpayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<bool> returnshipment
        {
            get
            {
                return this.returnshipmentField;
            }
            set
            {
                this.returnshipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnshipmentSpecified
        {
            get
            {
                return this.returnshipmentFieldSpecified;
            }
            set
            {
                this.returnshipmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> returnlabel
        {
            get
            {
                return this.returnlabelField;
            }
            set
            {
                this.returnlabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool returnlabelSpecified
        {
            get
            {
                return this.returnlabelFieldSpecified;
            }
            set
            {
                this.returnlabelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<bool> saturdayshipment
        {
            get
            {
                return this.saturdayshipmentField;
            }
            set
            {
                this.saturdayshipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool saturdayshipmentSpecified
        {
            get
            {
                return this.saturdayshipmentFieldSpecified;
            }
            set
            {
                this.saturdayshipmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string servicename
        {
            get
            {
                return this.servicenameField;
            }
            set
            {
                this.servicenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string deliveryremark
        {
            get
            {
                return this.deliveryremarkField;
            }
            set
            {
                this.deliveryremarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public ShipmentPickup shipmentpickup
        {
            get
            {
                return this.shipmentpickupField;
            }
            set
            {
                this.shipmentpickupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<bool> tel
        {
            get
            {
                return this.telField;
            }
            set
            {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool telSpecified
        {
            get
            {
                return this.telFieldSpecified;
            }
            set
            {
                this.telFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string deliverytype
        {
            get
            {
                return this.deliverytypeField;
            }
            set
            {
                this.deliverytypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=17)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public ShipmentService[] services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int codattribute
        {
            get
            {
                return this.codattributeField;
            }
            set
            {
                this.codattributeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class Cod
    {
        
        private string codretbankaccField;
        
        private string codretbankcodeField;
        
        private string codvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codretbankacc
        {
            get
            {
                return this.codretbankaccField;
            }
            set
            {
                this.codretbankaccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codretbankcode
        {
            get
            {
                return this.codretbankcodeField;
            }
            set
            {
                this.codretbankcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codvalue
        {
            get
            {
                return this.codvalueField;
            }
            set
            {
                this.codvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class CreateOrderResult
    {
        
        private string errorField;
        
        private string reffNrsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string reffNrs
        {
            get
            {
                return this.reffNrsField;
            }
            set
            {
                this.reffNrsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class WebServiceSddPrintResult
    {
        
        private string errorsField;
        
        private string labelUrlField;
        
        private string reportsUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string labelUrl
        {
            get
            {
                return this.labelUrlField;
            }
            set
            {
                this.labelUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string reportsUrl
        {
            get
            {
                return this.reportsUrlField;
            }
            set
            {
                this.reportsUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class WebServicePrintResult
    {
        
        private string errorsField;
        
        private string documentUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string documentUrl
        {
            get
            {
                return this.documentUrlField;
            }
            set
            {
                this.documentUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class FinishAndPrintOrdersResult
    {
        
        private CreateCifShipmentResult[] resultsField;
        
        private WebServicePrintResult printResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public CreateCifShipmentResult[] results
        {
            get
            {
                return this.resultsField;
            }
            set
            {
                this.resultsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public WebServicePrintResult printResult
        {
            get
            {
                return this.printResultField;
            }
            set
            {
                this.printResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class CreateCifShipmentResult
    {
        
        private PackageInfo[] packageInfoField;
        
        private WebServiceShipmnetResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public PackageInfo[] packageInfo
        {
            get
            {
                return this.packageInfoField;
            }
            set
            {
                this.packageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public WebServiceShipmnetResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class PackageInfo
    {
        
        private string refNrField;
        
        private string shipNrField;
        
        private System.Nullable<int> packageNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string refNr
        {
            get
            {
                return this.refNrField;
            }
            set
            {
                this.refNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string shipNr
        {
            get
            {
                return this.shipNrField;
            }
            set
            {
                this.shipNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> packageNo
        {
            get
            {
                return this.packageNoField;
            }
            set
            {
                this.packageNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class WebServiceShipmnetResult
    {
        
        private string errorsField;
        
        private string warningsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string warnings
        {
            get
            {
                return this.warningsField;
            }
            set
            {
                this.warningsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class MipWebserviceUploadResult
    {
        
        private int numberofmippackagesField;
        
        private int numberofmipshipmentField;
        
        private WebServiceShipmnetResult shipmentresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int numberofmippackages
        {
            get
            {
                return this.numberofmippackagesField;
            }
            set
            {
                this.numberofmippackagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int numberofmipshipment
        {
            get
            {
                return this.numberofmipshipmentField;
            }
            set
            {
                this.numberofmipshipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public WebServiceShipmnetResult shipmentresult
        {
            get
            {
                return this.shipmentresultField;
            }
            set
            {
                this.shipmentresultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class MipWebservicePackage
    {
        
        private string refnr1Field;
        
        private string refnr2Field;
        
        private string refnr3Field;
        
        private string scannedbarcodeField;
        
        private string weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string refnr1
        {
            get
            {
                return this.refnr1Field;
            }
            set
            {
                this.refnr1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string refnr2
        {
            get
            {
                return this.refnr2Field;
            }
            set
            {
                this.refnr2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string refnr3
        {
            get
            {
                return this.refnr3Field;
            }
            set
            {
                this.refnr3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string scannedbarcode
        {
            get
            {
                return this.scannedbarcodeField;
            }
            set
            {
                this.scannedbarcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class MipWebserviceAddress
    {
        
        private string appellationField;
        
        private string cityField;
        
        private string contactpersonField;
        
        private string countryField;
        
        private string emailField;
        
        private string housenrField;
        
        private string housenrextField;
        
        private string mobileField;
        
        private string name1Field;
        
        private string name2Field;
        
        private string name3Field;
        
        private string name4Field;
        
        private string name5Field;
        
        private string name6Field;
        
        private string notusedField;
        
        private string phoneField;
        
        private string streetField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string appellation
        {
            get
            {
                return this.appellationField;
            }
            set
            {
                this.appellationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string contactperson
        {
            get
            {
                return this.contactpersonField;
            }
            set
            {
                this.contactpersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string housenr
        {
            get
            {
                return this.housenrField;
            }
            set
            {
                this.housenrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string housenrext
        {
            get
            {
                return this.housenrextField;
            }
            set
            {
                this.housenrextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string name1
        {
            get
            {
                return this.name1Field;
            }
            set
            {
                this.name1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string name2
        {
            get
            {
                return this.name2Field;
            }
            set
            {
                this.name2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string name3
        {
            get
            {
                return this.name3Field;
            }
            set
            {
                this.name3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string name4
        {
            get
            {
                return this.name4Field;
            }
            set
            {
                this.name4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string name5
        {
            get
            {
                return this.name5Field;
            }
            set
            {
                this.name5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string name6
        {
            get
            {
                return this.name6Field;
            }
            set
            {
                this.name6Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string notused
        {
            get
            {
                return this.notusedField;
            }
            set
            {
                this.notusedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class MipWebserviceCod
    {
        
        private string codattrField;
        
        private string codretbankaccField;
        
        private string codretbankcodeField;
        
        private string codvalueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string codattr
        {
            get
            {
                return this.codattrField;
            }
            set
            {
                this.codattrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string codretbankacc
        {
            get
            {
                return this.codretbankaccField;
            }
            set
            {
                this.codretbankaccField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string codretbankcode
        {
            get
            {
                return this.codretbankcodeField;
            }
            set
            {
                this.codretbankcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string codvalue
        {
            get
            {
                return this.codvalueField;
            }
            set
            {
                this.codvalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class MipWebserviceShipment
    {
        
        private string cargo24hField;
        
        private string cargoattrField;
        
        private MipWebserviceCod codField;
        
        private MipWebserviceAddress consumerField;
        
        private string deliverydateField;
        
        private string deliveryremarkField;
        
        private string deliverytimefromField;
        
        private string deliverytimetoField;
        
        private string deliverytypeField;
        
        private string hypermarketField;
        
        private string insurcurrField;
        
        private string insurvalueField;
        
        private string internalnrtypeField;
        
        private string numberofeuropalettesField;
        
        private MipWebservicePackage[] packagesField;
        
        private string pdelyField;
        
        private string productdescField;
        
        private MipWebserviceAddress receiverField;
        
        private string receivernotifytypeField;
        
        private string recipientpayField;
        
        private string returnshipmentField;
        
        private string saturdayattrField;
        
        private string saturdayshipmentField;
        
        private MipWebserviceAddress senderField;
        
        private string servicenameField;
        
        private string shipdateField;
        
        private string shipinfo1Field;
        
        private string shipinfo2Field;
        
        private string shipinfo3Field;
        
        private string shipinfo4Field;
        
        private string telField;
        
        private string unitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cargo24h
        {
            get
            {
                return this.cargo24hField;
            }
            set
            {
                this.cargo24hField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string cargoattr
        {
            get
            {
                return this.cargoattrField;
            }
            set
            {
                this.cargoattrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public MipWebserviceCod cod
        {
            get
            {
                return this.codField;
            }
            set
            {
                this.codField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public MipWebserviceAddress consumer
        {
            get
            {
                return this.consumerField;
            }
            set
            {
                this.consumerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string deliverydate
        {
            get
            {
                return this.deliverydateField;
            }
            set
            {
                this.deliverydateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string deliveryremark
        {
            get
            {
                return this.deliveryremarkField;
            }
            set
            {
                this.deliveryremarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string deliverytimefrom
        {
            get
            {
                return this.deliverytimefromField;
            }
            set
            {
                this.deliverytimefromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string deliverytimeto
        {
            get
            {
                return this.deliverytimetoField;
            }
            set
            {
                this.deliverytimetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string deliverytype
        {
            get
            {
                return this.deliverytypeField;
            }
            set
            {
                this.deliverytypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string hypermarket
        {
            get
            {
                return this.hypermarketField;
            }
            set
            {
                this.hypermarketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string insurcurr
        {
            get
            {
                return this.insurcurrField;
            }
            set
            {
                this.insurcurrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string insurvalue
        {
            get
            {
                return this.insurvalueField;
            }
            set
            {
                this.insurvalueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string internalnrtype
        {
            get
            {
                return this.internalnrtypeField;
            }
            set
            {
                this.internalnrtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string numberofeuropalettes
        {
            get
            {
                return this.numberofeuropalettesField;
            }
            set
            {
                this.numberofeuropalettesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public MipWebservicePackage[] packages
        {
            get
            {
                return this.packagesField;
            }
            set
            {
                this.packagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string pdely
        {
            get
            {
                return this.pdelyField;
            }
            set
            {
                this.pdelyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string productdesc
        {
            get
            {
                return this.productdescField;
            }
            set
            {
                this.productdescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public MipWebserviceAddress receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string receivernotifytype
        {
            get
            {
                return this.receivernotifytypeField;
            }
            set
            {
                this.receivernotifytypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string recipientpay
        {
            get
            {
                return this.recipientpayField;
            }
            set
            {
                this.recipientpayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string returnshipment
        {
            get
            {
                return this.returnshipmentField;
            }
            set
            {
                this.returnshipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string saturdayattr
        {
            get
            {
                return this.saturdayattrField;
            }
            set
            {
                this.saturdayattrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string saturdayshipment
        {
            get
            {
                return this.saturdayshipmentField;
            }
            set
            {
                this.saturdayshipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public MipWebserviceAddress sender
        {
            get
            {
                return this.senderField;
            }
            set
            {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string servicename
        {
            get
            {
                return this.servicenameField;
            }
            set
            {
                this.servicenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string shipdate
        {
            get
            {
                return this.shipdateField;
            }
            set
            {
                this.shipdateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string shipinfo1
        {
            get
            {
                return this.shipinfo1Field;
            }
            set
            {
                this.shipinfo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string shipinfo2
        {
            get
            {
                return this.shipinfo2Field;
            }
            set
            {
                this.shipinfo2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string shipinfo3
        {
            get
            {
                return this.shipinfo3Field;
            }
            set
            {
                this.shipinfo3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string shipinfo4
        {
            get
            {
                return this.shipinfo4Field;
            }
            set
            {
                this.shipinfo4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string tel
        {
            get
            {
                return this.telField;
            }
            set
            {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string units
        {
            get
            {
                return this.unitsField;
            }
            set
            {
                this.unitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class CreateAndPrintCifShipmentWithSettingsResult
    {
        
        private PackageInfo[] packageInfoField;
        
        private WebServiceShipmnetResult resultField;
        
        private string documentUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public PackageInfo[] packageInfo
        {
            get
            {
                return this.packageInfoField;
            }
            set
            {
                this.packageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public WebServiceShipmnetResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string documentUrl
        {
            get
            {
                return this.documentUrlField;
            }
            set
            {
                this.documentUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class PrintingSettings
    {
        
        private string zplResolutionField;
        
        private string pdfContentFormatField;
        
        private string fileFormatField;
        
        private string paperFormatField;
        
        private string printFromPosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string zplResolution
        {
            get
            {
                return this.zplResolutionField;
            }
            set
            {
                this.zplResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string pdfContentFormat
        {
            get
            {
                return this.pdfContentFormatField;
            }
            set
            {
                this.pdfContentFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fileFormat
        {
            get
            {
                return this.fileFormatField;
            }
            set
            {
                this.fileFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string paperFormat
        {
            get
            {
                return this.paperFormatField;
            }
            set
            {
                this.paperFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string printFromPos
        {
            get
            {
                return this.printFromPosField;
            }
            set
            {
                this.printFromPosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class CreateAndPrintCifShipmentResult
    {
        
        private PackageInfo[] packageInfoField;
        
        private WebServiceShipmnetResult resultField;
        
        private string documentUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Namespace="http://server.webship.solver.sk", IsNullable=false)]
        public PackageInfo[] packageInfo
        {
            get
            {
                return this.packageInfoField;
            }
            set
            {
                this.packageInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public WebServiceShipmnetResult result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string documentUrl
        {
            get
            {
                return this.documentUrlField;
            }
            set
            {
                this.documentUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class ShipmentService
    {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class ShipmentPickup
    {
        
        private System.DateTime pickupstartdatetimeField;
        
        private System.DateTime pickupenddatetimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime pickupstartdatetime
        {
            get
            {
                return this.pickupstartdatetimeField;
            }
            set
            {
                this.pickupstartdatetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime pickupenddatetime
        {
            get
            {
                return this.pickupenddatetimeField;
            }
            set
            {
                this.pickupenddatetimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class WebServicePackage
    {
        
        private string reffnrField;
        
        private string weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string reffnr
        {
            get
            {
                return this.reffnrField;
            }
            set
            {
                this.reffnrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://customerData.webship.solver.sk")]
    public partial class ShipmentAddress
    {
        
        private string cityField;
        
        private string contactPersonField;
        
        private string countryField;
        
        private string emailField;
        
        private string mobileField;
        
        private string nameField;
        
        private string phoneField;
        
        private string streetField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string contactPerson
        {
            get
            {
                return this.contactPersonField;
            }
            set
            {
                this.contactPersonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="finishAndPrintOrders", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class finishAndPrintOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("refNumbers")]
        public string[] refNumbers;
        
        public finishAndPrintOrdersRequest()
        {
        }
        
        public finishAndPrintOrdersRequest(string name, string password, string[] refNumbers)
        {
            this.name = name;
            this.password = password;
            this.refNumbers = refNumbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="finishAndPrintOrdersResponse", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class finishAndPrintOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        public ServiceReference1.FinishAndPrintOrdersResult finishAndPrintOrdersReturn;
        
        public finishAndPrintOrdersResponse()
        {
        }
        
        public finishAndPrintOrdersResponse(ServiceReference1.FinishAndPrintOrdersResult finishAndPrintOrdersReturn)
        {
            this.finishAndPrintOrdersReturn = finishAndPrintOrdersReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCifShipments", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class createCifShipmentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("webServiceShipments")]
        public ServiceReference1.WebServiceShipment[] webServiceShipments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=3)]
        public int webServiceShipmentType;
        
        public createCifShipmentsRequest()
        {
        }
        
        public createCifShipmentsRequest(string name, string password, ServiceReference1.WebServiceShipment[] webServiceShipments, int webServiceShipmentType)
        {
            this.name = name;
            this.password = password;
            this.webServiceShipments = webServiceShipments;
            this.webServiceShipmentType = webServiceShipmentType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createCifShipmentsResponse", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class createCifShipmentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("createCifShipmentsReturn")]
        public ServiceReference1.CreateCifShipmentResult[] createCifShipmentsReturn;
        
        public createCifShipmentsResponse()
        {
        }
        
        public createCifShipmentsResponse(ServiceReference1.CreateCifShipmentResult[] createCifShipmentsReturn)
        {
            this.createCifShipmentsReturn = createCifShipmentsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrders", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class createOrdersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("webServiceShipments")]
        public ServiceReference1.WebServiceShipment[] webServiceShipments;
        
        public createOrdersRequest()
        {
        }
        
        public createOrdersRequest(string name, string password, ServiceReference1.WebServiceShipment[] webServiceShipments)
        {
            this.name = name;
            this.password = password;
            this.webServiceShipments = webServiceShipments;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrdersResponse", WrapperNamespace="http://server.webship.solver.sk", IsWrapped=true)]
    public partial class createOrdersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server.webship.solver.sk", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("createOrdersReturn")]
        public ServiceReference1.CreateOrderResult[] createOrdersReturn;
        
        public createOrdersResponse()
        {
        }
        
        public createOrdersResponse(ServiceReference1.CreateOrderResult[] createOrdersReturn)
        {
            this.createOrdersReturn = createOrdersReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WebshipWebServiceChannel : ServiceReference1.WebshipWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebshipWebServiceClient : System.ServiceModel.ClientBase<ServiceReference1.WebshipWebService>, ServiceReference1.WebshipWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebshipWebServiceClient() : 
                base(WebshipWebServiceClient.GetDefaultBinding(), WebshipWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WebshipWebService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebshipWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(WebshipWebServiceClient.GetBindingForEndpoint(endpointConfiguration), WebshipWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebshipWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebshipWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebshipWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebshipWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebshipWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> testAsync(string test)
        {
            return base.Channel.testAsync(test);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServiceShipmnetResult> createShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, int webServiceShipmentType)
        {
            return base.Channel.createShipmentAsync(name, password, webServiceShipment, webServiceShipmentType);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateCifShipmentResult> createCifShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, int webServiceShipmentType)
        {
            return base.Channel.createCifShipmentAsync(name, password, webServiceShipment, webServiceShipmentType);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentResult> createAndPrintCifShipmentAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment)
        {
            return base.Channel.createAndPrintCifShipmentAsync(name, password, webServiceShipment);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentWithSettingsResult> createAndPrintCifShipmentWithSettingsAsync(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, ServiceReference1.PrintingSettings printingSettings)
        {
            return base.Channel.createAndPrintCifShipmentWithSettingsAsync(name, password, webServiceShipment, printingSettings);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CreateAndPrintCifShipmentResult> createAndPrintCifShipmentWithSettings2Async(string name, string password, ServiceReference1.WebServiceShipment webServiceShipment, ServiceReference1.PrintingSettings printingSettings)
        {
            return base.Channel.createAndPrintCifShipmentWithSettings2Async(name, password, webServiceShipment, printingSettings);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServiceShipmnetResult> createMipShipmentAsync(string name, string password, ServiceReference1.MipWebserviceShipment mipWebserviceShipment)
        {
            return base.Channel.createMipShipmentAsync(name, password, mipWebserviceShipment);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MipWebserviceUploadResult> uploadMipShipmentsAsync(string name, string password)
        {
            return base.Channel.uploadMipShipmentsAsync(name, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.finishAndPrintOrdersResponse> ServiceReference1.WebshipWebService.finishAndPrintOrdersAsync(ServiceReference1.finishAndPrintOrdersRequest request)
        {
            return base.Channel.finishAndPrintOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.finishAndPrintOrdersResponse> finishAndPrintOrdersAsync(string name, string password, string[] refNumbers)
        {
            ServiceReference1.finishAndPrintOrdersRequest inValue = new ServiceReference1.finishAndPrintOrdersRequest();
            inValue.name = name;
            inValue.password = password;
            inValue.refNumbers = refNumbers;
            return ((ServiceReference1.WebshipWebService)(this)).finishAndPrintOrdersAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServiceSddPrintResult> printSDDshipmentsAsync(string aUserName, string aPassword)
        {
            return base.Channel.printSDDshipmentsAsync(aUserName, aPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printLabelsWithSettingsAsync(string aUserName, string aPassword, ServiceReference1.PrintingSettings aPrintingSettings)
        {
            return base.Channel.printLabelsWithSettingsAsync(aUserName, aPassword, aPrintingSettings);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printShipmentLabelsAsync(string aUserName, string aPassword)
        {
            return base.Channel.printShipmentLabelsAsync(aUserName, aPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WebServicePrintResult> printEndOfDayAsync(string aUserName, string aPassword)
        {
            return base.Channel.printEndOfDayAsync(aUserName, aPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createCifShipmentsResponse> ServiceReference1.WebshipWebService.createCifShipmentsAsync(ServiceReference1.createCifShipmentsRequest request)
        {
            return base.Channel.createCifShipmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.createCifShipmentsResponse> createCifShipmentsAsync(string name, string password, ServiceReference1.WebServiceShipment[] webServiceShipments, int webServiceShipmentType)
        {
            ServiceReference1.createCifShipmentsRequest inValue = new ServiceReference1.createCifShipmentsRequest();
            inValue.name = name;
            inValue.password = password;
            inValue.webServiceShipments = webServiceShipments;
            inValue.webServiceShipmentType = webServiceShipmentType;
            return ((ServiceReference1.WebshipWebService)(this)).createCifShipmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createOrdersResponse> ServiceReference1.WebshipWebService.createOrdersAsync(ServiceReference1.createOrdersRequest request)
        {
            return base.Channel.createOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.createOrdersResponse> createOrdersAsync(string name, string password, ServiceReference1.WebServiceShipment[] webServiceShipments)
        {
            ServiceReference1.createOrdersRequest inValue = new ServiceReference1.createOrdersRequest();
            inValue.name = name;
            inValue.password = password;
            inValue.webServiceShipments = webServiceShipments;
            return ((ServiceReference1.WebshipWebService)(this)).createOrdersAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebshipWebService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebshipWebService))
            {
                return new System.ServiceModel.EndpointAddress("https://webship.sps-sro.sk/services/WebshipWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebshipWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.WebshipWebService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebshipWebServiceClient.GetEndpointAddress(EndpointConfiguration.WebshipWebService);
        }
        
        public enum EndpointConfiguration
        {
            
            WebshipWebService,
        }
    }
}
