//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Webtrace
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Shipments", ConfigurationName="Webtrace.WebtracePortType")]
    public interface WebtracePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://t-t.sps-sro.sk/service_soap.php/getTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        System.Threading.Tasks.Task<Webtrace.getTestResponse> getTestAsync(Webtrace.getTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getListOfShipments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.Shipment[]> getListOfShipmentsAsync(int kundenr, string verknr, int km_mandr, [System.Xml.Serialization.SoapElementAttribute(DataType="date")] System.DateTime versdat, string langi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getShipmentDet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.Shipment> getShipmentDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getShipment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.Shipment> getShipmentAsync(int landnr, int mandnr, int lfdnr, string langi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getListOfParcelsDet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.Parcel[]> getListOfParcelsDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getListOfParcels", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.Parcel[]> getListOfParcelsAsync(int landnr, int mandnr, int lfdnr, string langi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getParcelStatusDet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.ParcelStatus[]> getParcelStatusDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#getParcelStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<Webtrace.ParcelStatus[]> getParcelStatusAsync(int landnr, int mandnr, int lfdnr, string langi);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Shipments#get_stredisko_dorucenia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ParcelStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Parcel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> get_stredisko_doruceniaAsync(int landnr, int mandnr, int lfdnr);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTest", WrapperNamespace="", IsWrapped=true)]
    public partial class getTestRequest
    {
        
        public getTestRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTestResponse", WrapperNamespace="", IsWrapped=true)]
    public partial class getTestResponse
    {
        
        public getTestResponse()
        {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Shipments")]
    public partial class Shipment
    {
        
        private string shipmentNumberField;
        
        private System.DateTime shippingDateField;
        
        private string destinationZipField;
        
        private string shipperField;
        
        private string receiverField;
        
        private string statusField;
        
        private int statusCodeField;
        
        private string nameOfReceiverField;
        
        private string referenceNumber1Field;
        
        private string referenceNumber2Field;
        
        private string referenceNumber3Field;
        
        private string referenceNumber4Field;
        
        private string barcodeField;
        
        private string internationalReferenceNumberField;
        
        private double weightField;
        
        /// <remarks/>
        public string ShipmentNumber
        {
            get
            {
                return this.shipmentNumberField;
            }
            set
            {
                this.shipmentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime ShippingDate
        {
            get
            {
                return this.shippingDateField;
            }
            set
            {
                this.shippingDateField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationZip
        {
            get
            {
                return this.destinationZipField;
            }
            set
            {
                this.destinationZipField = value;
            }
        }
        
        /// <remarks/>
        public string Shipper
        {
            get
            {
                return this.shipperField;
            }
            set
            {
                this.shipperField = value;
            }
        }
        
        /// <remarks/>
        public string Receiver
        {
            get
            {
                return this.receiverField;
            }
            set
            {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string NameOfReceiver
        {
            get
            {
                return this.nameOfReceiverField;
            }
            set
            {
                this.nameOfReceiverField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber1
        {
            get
            {
                return this.referenceNumber1Field;
            }
            set
            {
                this.referenceNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber2
        {
            get
            {
                return this.referenceNumber2Field;
            }
            set
            {
                this.referenceNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber3
        {
            get
            {
                return this.referenceNumber3Field;
            }
            set
            {
                this.referenceNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber4
        {
            get
            {
                return this.referenceNumber4Field;
            }
            set
            {
                this.referenceNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string InternationalReferenceNumber
        {
            get
            {
                return this.internationalReferenceNumberField;
            }
            set
            {
                this.internationalReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public double Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Shipments")]
    public partial class ParcelStatus
    {
        
        private string parcelNumberField;
        
        private System.DateTime dateField;
        
        private System.DateTime timeField;
        
        private string statusField;
        
        private int statusCodeXField;
        
        private string centerField;
        
        private string remarkField;
        
        private decimal geoLocXField;
        
        private decimal geoLocYField;
        
        /// <remarks/>
        public string ParcelNumber
        {
            get
            {
                return this.parcelNumberField;
            }
            set
            {
                this.parcelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="time")]
        public System.DateTime Time
        {
            get
            {
                return this.timeField;
            }
            set
            {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCodeX
        {
            get
            {
                return this.statusCodeXField;
            }
            set
            {
                this.statusCodeXField = value;
            }
        }
        
        /// <remarks/>
        public string Center
        {
            get
            {
                return this.centerField;
            }
            set
            {
                this.centerField = value;
            }
        }
        
        /// <remarks/>
        public string Remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public decimal GeoLocX
        {
            get
            {
                return this.geoLocXField;
            }
            set
            {
                this.geoLocXField = value;
            }
        }
        
        /// <remarks/>
        public decimal GeoLocY
        {
            get
            {
                return this.geoLocYField;
            }
            set
            {
                this.geoLocYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Shipments")]
    public partial class Parcel
    {
        
        private string parcelNumberField;
        
        private string statusField;
        
        private int statusCodeField;
        
        private string referenceNumber1Field;
        
        private string referenceNumber2Field;
        
        private string referenceNumber3Field;
        
        private string referenceNumber4Field;
        
        private string barcodeField;
        
        private string internationalReferenceNumberField;
        
        /// <remarks/>
        public string ParcelNumber
        {
            get
            {
                return this.parcelNumberField;
            }
            set
            {
                this.parcelNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int StatusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber1
        {
            get
            {
                return this.referenceNumber1Field;
            }
            set
            {
                this.referenceNumber1Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber2
        {
            get
            {
                return this.referenceNumber2Field;
            }
            set
            {
                this.referenceNumber2Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber3
        {
            get
            {
                return this.referenceNumber3Field;
            }
            set
            {
                this.referenceNumber3Field = value;
            }
        }
        
        /// <remarks/>
        public string ReferenceNumber4
        {
            get
            {
                return this.referenceNumber4Field;
            }
            set
            {
                this.referenceNumber4Field = value;
            }
        }
        
        /// <remarks/>
        public string Barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }
        
        /// <remarks/>
        public string InternationalReferenceNumber
        {
            get
            {
                return this.internationalReferenceNumberField;
            }
            set
            {
                this.internationalReferenceNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WebtracePortTypeChannel : Webtrace.WebtracePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WebtracePortTypeClient : System.ServiceModel.ClientBase<Webtrace.WebtracePortType>, Webtrace.WebtracePortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WebtracePortTypeClient() : 
                base(WebtracePortTypeClient.GetDefaultBinding(), WebtracePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WebtracePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebtracePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(WebtracePortTypeClient.GetBindingForEndpoint(endpointConfiguration), WebtracePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebtracePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WebtracePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebtracePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WebtracePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WebtracePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Webtrace.getTestResponse> Webtrace.WebtracePortType.getTestAsync(Webtrace.getTestRequest request)
        {
            return base.Channel.getTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Webtrace.getTestResponse> getTestAsync()
        {
            Webtrace.getTestRequest inValue = new Webtrace.getTestRequest();
            return ((Webtrace.WebtracePortType)(this)).getTestAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<Webtrace.Shipment[]> getListOfShipmentsAsync(int kundenr, string verknr, int km_mandr, System.DateTime versdat, string langi)
        {
            return base.Channel.getListOfShipmentsAsync(kundenr, verknr, km_mandr, versdat, langi);
        }
        
        public System.Threading.Tasks.Task<Webtrace.Shipment> getShipmentDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip)
        {
            return base.Channel.getShipmentDetAsync(landnr, mandnr, lfdnr, langi, km_mandr, kundenr, rec_zip);
        }
        
        public System.Threading.Tasks.Task<Webtrace.Shipment> getShipmentAsync(int landnr, int mandnr, int lfdnr, string langi)
        {
            return base.Channel.getShipmentAsync(landnr, mandnr, lfdnr, langi);
        }
        
        public System.Threading.Tasks.Task<Webtrace.Parcel[]> getListOfParcelsDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip)
        {
            return base.Channel.getListOfParcelsDetAsync(landnr, mandnr, lfdnr, langi, km_mandr, kundenr, rec_zip);
        }
        
        public System.Threading.Tasks.Task<Webtrace.Parcel[]> getListOfParcelsAsync(int landnr, int mandnr, int lfdnr, string langi)
        {
            return base.Channel.getListOfParcelsAsync(landnr, mandnr, lfdnr, langi);
        }
        
        public System.Threading.Tasks.Task<Webtrace.ParcelStatus[]> getParcelStatusDetAsync(int landnr, int mandnr, int lfdnr, string langi, int km_mandr, int kundenr, string rec_zip)
        {
            return base.Channel.getParcelStatusDetAsync(landnr, mandnr, lfdnr, langi, km_mandr, kundenr, rec_zip);
        }
        
        public System.Threading.Tasks.Task<Webtrace.ParcelStatus[]> getParcelStatusAsync(int landnr, int mandnr, int lfdnr, string langi)
        {
            return base.Channel.getParcelStatusAsync(landnr, mandnr, lfdnr, langi);
        }
        
        public System.Threading.Tasks.Task<int> get_stredisko_doruceniaAsync(int landnr, int mandnr, int lfdnr)
        {
            return base.Channel.get_stredisko_doruceniaAsync(landnr, mandnr, lfdnr);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebtracePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WebtracePort))
            {
                return new System.ServiceModel.EndpointAddress("http://t-t.sps-sro.sk/service_soap.php");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WebtracePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.WebtracePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WebtracePortTypeClient.GetEndpointAddress(EndpointConfiguration.WebtracePort);
        }
        
        public enum EndpointConfiguration
        {
            
            WebtracePort,
        }
    }
}
